DATA:
  LOAD_EXISTING: False
  PREDICTION_PARADIGM: X1X2_window
  N_SAMPLES: 100  # total number of data samples to generate, i.e. the sum of 
                  # all train, val, and test samples 
  INPUT_STEPS: 1
  OUTPUT_DELAY: 0
  OUTPUT_STEPS: 3
  TIMESTEP_DURATION: 4  # the sampling rate for data points from the raw Lorenz 
                        # simulation data. all data points are separated by this value. 
  SAMPLE_BUFFER: 10 # number of timesteps between the last target timestep 
                        # of the preceding sample and first input timestep of the next sample
  LORENZ:
    K: 36
    F: 8
    C: 10
    B: 10
    H: 1
    COUPLED: True
  TIME_RESOLUTION: 100 # the inverse of the delta t used in the Lorenz ODE integration (∆t = 1/time_resolution)
    # NOTE: Lorenz identified 1 time unit in the simulation as approximating 5 Earth days (from comparing error-doubling time); thus the time_resolution is equivalent to the number of data points generated per 5 days in the simulation. 
  BUFFER: 
    INIT_BUFFER_STEPS: 100
    RETURN_BUFFER: False
  SPLIT:
    TRAIN_PCT: 0.7
    VAL_PCT: 0.2
    TEST_PCT: 0.1
  SEED: 42
  OVERRIDE: False

MODEL:
  ARCH: MLP_graph_network 
  # ARCH options: naive_zero, naive_constant, MLP_graph_network, MLP_block
  SPATIAL: True 

OUTPUT_DIR: "outputs/"
LOG_LEVEL: DEBUG

TRAIN:
  ENABLE: True
  RESUME_FROM_CHECKPOINT: False
  # CHECKPOINT_FNAME: ""
  # if resume_from_checkpoint true and no explicit checkpoint, resume from the latest epoch
  MAX_EPOCHS: 5
  LOAD_PARAMS: False
  PARAM_PATH: ""

VAL:
  ENABLE: False
  # if checkpoint not explicitly passed, use latest output from train (i.e. latest epoch)
  # CHECKPOINT_FNAME: "INSERT"
  
TEST:
  ENABLE: True
  # CHECKPOINT_FNAME: "INSERT"
  # if checkpoint not explicitly passed, use latest output from train (i.e. latest epoch)
