DATA:
  LOAD_EXISTING: False
  DATA_PATH: INSERT
  PREDICTION_PARADIGM: X1X2_window
  N_SAMPLES: 20_000
  INPUT_STEPS: 1
  OUTPUT_DELAY: 0
  OUTPUT_STEPS: 0
  MIN_BUFFER: 0
  LORENZ:
    K: 36
    F: 8
    C: 10
    B: 10
    H: 1
    COUPLED: True
  TIME_RESOLUTION: 100
  BUFFER: 
    INIT_BUFFER_STEPS: 100
    RETURN_BUFFER: False
  SPLIT:
    TRAIN_PCT: 0.7
    VAL_PCT: 0.2
    TEST_PCT: 0.1
  N_ROLLOUT_STEPS: 2
  TIMESTEP_DURATION: 25
  SEED: 42
  OVERRIDE: False

MODEL:
  ARCH: MLP 
  # ARCH options: naive_zero, naive_constant, MLP
  SPATIAL: True 

OUTPUT_DIR: "outputs/"
TRAIN:
  ENABLE: True
  RESUME_FROM_CHECKPOINT: False
  # CHECKPOINT_FNAME: ""
  # if resume_from_checkpoint true and no explicit checkpoint, resume from the latest epoch
  MAX_EPOCHS: 2
  LOAD_PARAMS: False
  PARAM_PATH: ""

VAL:
  ENABLE: True
  # if checkpoint not explicitly passed, use latest output from train (i.e. latest epoch)
  # CHECKPOINT_FNAME: "INSERT"
  
TEST:
  ENABLE: True
  # CHECKPOINT_FNAME: "INSERT"
  # if checkpoint not explicitly passed, use latest output from train (i.e. latest epoch)
