DATA:
  LOAD_EXISTING: False
  DATA_PATH: INSERT
  PREDICTION_PARADIGM: X1X2_window
  N_SAMPLES: 20_000
  INPUT_STEPS: 1
  OUTPUT_DELAY: 0
  OUTPUT_STEPS: 0
  MIN_BUFFER: 0
  LORENZ:
    K: 36
    F: 8
    C: 10
    B: 10
    H: 1
    COUPLED: True
  TIME_RESOLUTION: 100
  BUFFER: 
    INIT_BUFFER_STEPS: 100
    RETURN_BUFFER: False
  SPLIT:
    TRAIN_PCT: 0.7
    VAL_PCT: 0.2
    TEST_PCT: 0.1
  SEED: 42

TRAIN:
  ENABLE: True
  RESUME_FROM_CHECKPOINT: False
  CHECKPOINT: ""
  MAX_EPOCHS: 100

VAL:
  ENABLE: True
  CHECKPOINT: "INSERT"
  
TEST:
  ENABLE: True
  CHECKPOINT: "INSERT"
